### ISSUE TITLE
Compiling VBB under OSX

### ISSUE THREAD

**Issue by rachel3834** [valboz/VBBinaryLensing#8]
After installing pybind and running python setup.up install, I get the following errors.  

VBBinaryLensing/lib/python_bindings.cpp:24:70: warning: unknown escape sequence
      '\s' [-Wunknown-escape-sequence]
  ..."Linear limb darkening coefficient. I(r)=I(0)(1-a1(1-\sqrt{1-r^2/\rho^2}...
                                                          ^~
VBBinaryLensing/lib/python_bindings.cpp:260:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:289:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:334:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:362:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:391:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:421:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:452:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:485:74: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
  ...y1s.data(), y2s.data(), separation.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:521:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:551:55: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
                        y1s.data(), y2s.data(), times.size());
                                                ~~~~~~^~~~~~
VBBinaryLensing/lib/python_bindings.cpp:583:74: warning: implicit conversion
      loses integer precision: 'std::__1::vector<double,
      std::__1::allocator<double> >::size_type' (aka 'unsigned long') to 'int'
      [-Wshorten-64-to-32]
  ...y1s.data(), y2s.data(), separation.data(), times.size());
                                                ~~~~~~^~~~~~
12 warnings generated.
VBBinaryLensing/lib/python_bindings.cpp:24:70: warning: unknown escape sequence
      '\s' [-Wunknown-escape-sequence]
  ..."Linear limb darkening coefficient. I(r)=I(0)(1-a1(1-\sqrt{1-r^2/\rho^2}...
                                                          ^~
1 warning generated.
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:330:28: error: 
      a non-type template parameter cannot have type 'class x1'
template <class _L0, class _L1>
                           ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:330:28: error: 
      expected ',' or '>' in template-parameter-list
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:332:21: error: 
      expected ')'
try_lock(_L0& __l0, _L1& __l1)
                    ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:332:9: note: 
      to match this '('
try_lock(_L0& __l0, _L1& __l1)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:332:21: error: 
      variable has incomplete type 'std::__1::x1'
try_lock(_L0& __l0, _L1& __l1)
                    ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:330:28: note: 
      forward declaration of 'std::__1::x1'
template <class _L0, class _L1>
                           ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:13: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
            ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:337:13: error: 
      use of undeclared identifier '__l1'; did you mean '__l0'?
        if (__l1.try_lock())
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:332:15: note: 
      '__l0' declared here
try_lock(_L0& __l0, _L1& __l1)
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:350:28: error: 
      a non-type template parameter cannot have type 'class x1'
template <class _L0, class _L1, class _L2, class... _L3>
                           ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:350:28: error: 
      expected ',' or '>' in template-parameter-list
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:23:15: note: expanded from macro
      '_L1'
#define _L1 x1-((x1+a/2.0)/((x1+a/2.0)*(x1+a/2.0)+x2*x2)+q*(x1-a/2.0)/((...
              ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:33:
In file included from /Users/rstreet/software/pylima-venv/venv/include/site/python2.7/pybind11/stl.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:18:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:350:31: error: 
      expected unqualified-id
template <class _L0, class _L1, class _L2, class... _L3>
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/mutex:558:16: error: 
      unknown type name 'once_flag'
void call_once(once_flag&, _Callable&&, _Args&&...);
               ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:347:6: warning: unused variable
      'c' [-Wunused-variable]
        int c = 0, ic;
            ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:495:37: warning: unused variable
      'cq' [-Wunused-variable]
        static double av = -1.0, qv = -1.0,cq;
                                           ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:753:6: warning: unused variable
      'c' [-Wunused-variable]
        int c = 0;
            ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1028:6: warning: unused variable
      'c' [-Wunused-variable]
        int c = 0;
            ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1058:15: warning: unused variable
      'totNPS' [-Wunused-variable]
        int nannold, totNPS = 1;
                     ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1380:161: warning: unused
      variable 'w3' [-Wunused-variable]
  ...u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr[9], w3 = pr[10];
                                                                ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1380:137: warning: unused
      variable 'w1' [-Wunused-variable]
  ...= exp(pr[1]), tn, u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr...
                                                          ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1380:149: warning: unused
      variable 'w2' [-Wunused-variable]
  ...tn, u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr[9], w3 = pr[10];
                                                        ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1651:161: warning: unused
      variable 'w3' [-Wunused-variable]
  ...u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr[9], w3 = pr[10];
                                                                ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1651:149: warning: unused
      variable 'w2' [-Wunused-variable]
  ...tn, u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr[9], w3 = pr[10];
                                                        ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1651:137: warning: unused
      variable 'w1' [-Wunused-variable]
  ...= exp(pr[1]), tn, u, u0, pai1 = pr[6], pai2 = pr[7], w1 = pr[8], w2 = pr...
                                                          ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1794:44: warning: unused variable
      'disisso' [-Wunused-variable]
        static double av = 0.0, m1v = 0.0, disim, disisso;
                                                  ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1794:16: warning: unused variable
      'av' [-Wunused-variable]
        static double av = 0.0, m1v = 0.0, disim, disisso;
                      ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:1794:26: warning: unused variable
      'm1v' [-Wunused-variable]
        static double av = 0.0, m1v = 0.0, disim, disisso;
                                ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:2009:32: warning: unused variable
      'scan3' [-Wunused-variable]
        static _point *scan, *scan2, *scan3, *isso[2];
                                      ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:3205:16: warning: unused variable
      'j' [-Wunused-variable]
        static int i, j, k;
                      ^
In file included from VBBinaryLensing/lib/VBBinaryLensingLibrary.cpp:26:
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:10: warning: private field 'e'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                       ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:12: warning: private field 'phi'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                         ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:16: warning: private field
      'phip' is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                             ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:21: warning: private field
      'phi0' is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                  ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:26: warning: private field 'Om'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                       ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:29: warning: private field 'inc'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                          ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:36: warning: private field 'd3'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                                 ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:39: warning: private field 'v3'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                                    ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:42: warning: private field 'GM'
      is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                                       ^
VBBinaryLensing/lib/VBBinaryLensingLibrary.h:56:45: warning: private field
      'flagits' is not used [-Wunused-private-field]
                double e,phi,phip,phi0,Om,inc,t0,d3,v3,GM,flagits;
                                                          ^
26 warnings and 9 errors generated.
error: command '/usr/bin/cc' failed with exit status 1

**Comment by fbartolic** [comment]
Hi Rachael. I've noticed that the package doesn't install under OSX, unfortunately, I have zero experience with Macs. This issue has to do something with C++ compilation options. I'll try to look into it by the end of the week.

**Comment by rachel3834** [comment]
Thanks Fran!  When I have time I will help to investigate but I am rather swamped at the moment.

**Comment by fbartolic** [comment]
Hi @rachel3834 , can you try installing it now, it should work as of b05f265e2ff82a4ca3db66f05c960ff8e547ce8a . If it compiles successfully run `py.test` and see if the tests
are passing.

**Comment by rachel3834** [comment]
I created a virtualenv and installed the code from scratch within that env, to ensure it was tested from scratch.  I include the output from this process below.  I tried running py.test but got no output - this will need a path to be effective.  However, as far as I can see the process attempted to download and install pybind11 and VBB, but did not complete.  

(test_vbb) Rachels-MacBook-Pro-2:test_vbb rstreet$ pip install VBBinaryLensing
Collecting VBBinaryLensing
  Downloading https://files.pythonhosted.org/packages/29/eb/d9e8cf7da61681e469b971d8d2580088dd9cc5cac984482118d0f677804d/VBBinaryLensing-2.0.5.tar.gz
Collecting pybind11>=2.2 (from VBBinaryLensing)
  Using cached https://files.pythonhosted.org/packages/12/90/0f92a575dc60c8fba6d0c91d6b45abdb1058da9ebed40400cbcfad2ac0a7/pybind11-2.2.3-py2.py3-none-any.whl
Building wheels for collected packages: VBBinaryLensing
  Running setup.py bdist_wheel for VBBinaryLensing ... error
  Complete output from command /Users/rstreet/software/test_vbb/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/tmp/pip-install-_07Hjy/VBBinaryLensing/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/tmp/pip-wheel-jDJ7bJ --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  creating var
  creating var/tmp
  /usr/bin/cc -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /var/tmp/tmpUItDyk.cpp -o var/tmp/tmpUItDyk.o -std=c++14
  /usr/bin/cc -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /var/tmp/tmpPidA25.cpp -o var/tmp/tmpPidA25.o -fvisibility=hidden
  building 'VBBinaryLensing' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/tmp/pip-install-_07Hjy/VBBinaryLensing/setup.py", line 105, in <module>
      zip_safe=False,
    File "/Users/rstreet/software/test_vbb/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/rstreet/software/test_vbb/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/rstreet/software/test_vbb/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
      self.build_extensions()
    File "/private/var/tmp/pip-install-_07Hjy/VBBinaryLensing/setup.py", line 91, in build_extensions
      build_ext.build_extensions(self)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
      self.build_extension(ext)
    File "/Users/rstreet/software/test_vbb/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
      depends=ext.depends)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 566, in compile
      depends, extra_postargs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 355, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 1051, in gen_preprocess_options
      pp_opts.append ("-I%s" % dir)
    File "/private/var/tmp/pip-install-_07Hjy/VBBinaryLensing/setup.py", line 21, in __str__
      import pybind11
  ImportError: No module named pybind11
  
  ----------------------------------------
  Failed building wheel for VBBinaryLensing
  Running setup.py clean for VBBinaryLensing
Failed to build VBBinaryLensing
Installing collected packages: pybind11, VBBinaryLensing
  Running setup.py install for VBBinaryLensing ... done
Successfully installed VBBinaryLensing-2.0.5 pybind11-2.2.3
